version: '3.8'

services:
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    environment:
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"]
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./apps/backend:/app
      - /app/node_modules  # anonymous volume to prevent host interference
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - OLLAMA_CHAT_MODEL=llama3.2
      - OLLAMA_EMBEDDING_MODEL=llama3.2
      - CHROMA_COLLECTION_NAME=your-collection-name
      - CHROMA_SERVER_URL=http://chroma:8000
      - SERVER_PORT=3000
      - SERVER_HOST=0.0.0.0

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - SERVER_PORT=3000
      - SERVER_HOST=0.0.0.0
      - VITE_API_URL=http://localhost:3000

volumes:
  chroma_data:
